### ISSUE TITLE
Cannot read properties of undefined (reading 'newRawInstance') when one to many relation (SSR)

### ISSUE THREAD

**Issue by adinvadim** [CodeDredd/pinia-orm#476]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-hrsy4e?file=app.vue

### Describe the bug

Error "Cannot read properties of undefined (reading 'newRawInstance')" on models with one-to-many relations

### Additional context

This error threw only in SSR

**Comment by adinvadim** [comment]
```
export * from './Group';
export * from './Item';

→ 
export {GroupModel} from './Group';
export {ItemModel} from './Item';
```

I don't know how, but this change fix error

**Comment by CodeDredd** [comment]
The reason for this error is that the they you did it your defining the order how modules should be loaded. Since `Group Model` is loaded first and `Item Model` second, but `Group Model` needs `Item Model` it fails. If you change the order you will find out that it works.
The other `fix` by you works because now the exports are treated as singelton.

You can find more information about that in this [article](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de) for example.

There a problem with circular dependency is fixed and explained how it works.
